// GENERATED by scripts/generate-blog-index.mjs — do not hand-edit.
// Re-run `node scripts/generate-blog-index.mjs` after adding/removing/retitling blog posts.
// Sources: app/blog/<slug>/page.mdx (static routes) + content/blog/<file>.md
// (the larger primary source, filtered the same way app/sitemap.ts filters it:
// haiku-/cerebras- batches and lib/noindex-reprints.ts excluded). Static-route
// slugs win over content/blog on collision.

export interface BlogIndexEntry {
  slug: string
  title: string
  category: string
  tags: string[]
}

export const BLOG_INDEX: BlogIndexEntry[] = [
  {
    "slug": "01-best-healthcare-reits-medical-properties-2026",
    "title": "Best Healthcare REITs Medical Properties 2026",
    "category": "",
    "tags": []
  },
  {
    "slug": "01-best-monthly-dividend-stocks-2026",
    "title": "Best Monthly Dividend Stocks 2026: Top Picks for Consistent Income",
    "category": "Dividend Investing",
    "tags": []
  },
  {
    "slug": "01-dollar-cost-averaging-dividend-stocks-strategy-2026",
    "title": "Dollar Cost Averaging Dividend Stocks Strategy: Complete 2026 Guide",
    "category": "dividend-strategies",
    "tags": []
  },
  {
    "slug": "01-drip-investing-for-beginners-2026",
    "title": "DRIP Investing for Beginners 2026: Your Complete Starting Guide",
    "category": "",
    "tags": []
  },
  {
    "slug": "02-top-10-dividend-aristocrats-analysis",
    "title": "Top 9 Dividend Aristocrats Analysis 2026: The Elite Dividend Stocks",
    "category": "",
    "tags": []
  },
  {
    "slug": "02-top-10-dividend-etfs-for-passive-income",
    "title": "Top 10 Dividend ETFs for Passive Income: 2026 Investment Guide",
    "category": "Dividend Investing",
    "tags": []
  },
  {
    "slug": "02-top-biotech-dividend-stocks-high-yield",
    "title": "Top biotech dividend stocks high yield",
    "category": "Calc",
    "tags": []
  },
  {
    "slug": "03-best-dividend-stocks-under-50",
    "title": "Best Dividend Stocks Under $50: Affordable Income Investing in 2026",
    "category": "Dividend Investing",
    "tags": []
  },
  {
    "slug": "03-monthly-dividend-stocks-guide",
    "title": "Monthly Dividend Stocks Guide 2026: Build Monthly Income Today",
    "category": "",
    "tags": []
  },
  {
    "slug": "04-high-yield-reits-worth-buying",
    "title": "High-Yield REITs Worth Buying in 2026: Best Real Estate Dividends",
    "category": "Dividend Investing",
    "tags": []
  },
  {
    "slug": "04-reits-vs-dividend-stocks",
    "title": "REITs vs Dividend Stocks: Complete Comparison Guide 2026",
    "category": "",
    "tags": []
  },
  {
    "slug": "05-tax-efficient-dividend-investing",
    "title": "Tax-Efficient Dividend Investing 2026: Maximize Your After-Tax Returns",
    "category": "",
    "tags": []
  },
  {
    "slug": "06-dividend-growth-strategy",
    "title": "Dividend Growth Strategy 2026: Build Wealth Through Increasing Dividends",
    "category": "",
    "tags": []
  },
  {
    "slug": "06-top-canadian-dividend-stocks",
    "title": "Top Canadian Dividend Stocks: 2026 Guide to North American Income",
    "category": "Dividend Investing",
    "tags": []
  },
  {
    "slug": "07-best-dividend-growth-stocks-2026",
    "title": "Best Dividend Growth Stocks 2026: Build Wealth Through Dividend Increases",
    "category": "Dividend Investing",
    "tags": []
  },
  {
    "slug": "07-high-yield-vs-dividend-growth",
    "title": "High Yield vs Dividend Growth: Which Strategy Wins? 2026 Analysis",
    "category": "",
    "tags": []
  },
  {
    "slug": "08-building-1k-monthly-dividend-income",
    "title": "Building $1K Monthly Dividend Income: The Complete Roadmap 2026",
    "category": "",
    "tags": []
  },
  {
    "slug": "08-drip-calculator-annual-vs-monthly-reinvestment-timing",
    "title": "What DRIP Timing Actually Costs You: Annual vs. Monthly Reinvestment",
    "category": "dividend-strategies",
    "tags": []
  },
  {
    "slug": "08-top-technology-dividend-stocks",
    "title": "Top Technology Dividend Stocks 2026: High Growth Meets Income",
    "category": "Dividend Investing",
    "tags": []
  },
  {
    "slug": "09-best-consumer-goods-dividend-stocks",
    "title": "Best Consumer Goods Dividend Stocks: Defensive & Growing",
    "category": "Dividend Investing",
    "tags": []
  },
  {
    "slug": "09-best-healthcare-dividend-stocks",
    "title": "Best Healthcare Dividend Stocks 2026: Aging Population Wealth",
    "category": "Dividend Investing",
    "tags": []
  },
  {
    "slug": "09-retirement-income-from-dividends",
    "title": "Retirement Income from Dividends: The Dividend-Only Retirement Plan 2026",
    "category": "",
    "tags": []
  },
  {
    "slug": "10-dividend-reinvestment-calculator-guide",
    "title": "Complete Guide to Using the Dividend Reinvestment Calculator 2026",
    "category": "",
    "tags": []
  },
  {
    "slug": "10-top-utility-dividend-stocks",
    "title": "Top Utility Dividend Stocks 2026: Reliable Income and Growth",
    "category": "Dividend Investing",
    "tags": []
  },
  {
    "slug": "13-how-to-replace-a-100000-salary-with-dividend-incomestep-guid",
    "title": "How to Replace a $100,000 Salary With Dividend Income: Step Guide",
    "category": "Articles",
    "tags": []
  },
  {
    "slug": "16-how-to-build-1000-month-dividend-portfolio",
    "title": "How to Build a $1,000/Month Dividend Portfolio",
    "category": "Investment Guides",
    "tags": []
  },
  {
    "slug": "17-how-to-calculate-dividend-yield-correctly",
    "title": "How to Calculate Dividend Yield Correctly",
    "category": "Investment Guides",
    "tags": []
  },
  {
    "slug": "18-how-to-find-dividend-stocks-before-popular",
    "title": "How to Find Dividend Stocks Before They're Popular",
    "category": "Investment Guides",
    "tags": []
  },
  {
    "slug": "19-how-to-analyze-dividend-safety",
    "title": "How to Analyze Dividend Safety",
    "category": "Investment Guides",
    "tags": []
  },
  {
    "slug": "20-how-to-time-dividend-purchases-ex-dividend-dates",
    "title": "How to Time Dividend Purchases (Ex-Dividend Dates)",
    "category": "Investment Guides",
    "tags": []
  },
  {
    "slug": "21-how-to-build-dividend-ladder",
    "title": "How to Build a Dividend Ladder",
    "category": "Investment Guides",
    "tags": []
  },
  {
    "slug": "22-how-to-reinvest-dividends-maximum-growth",
    "title": "How to Reinvest Dividends for Maximum Growth",
    "category": "Investment Guides",
    "tags": []
  },
  {
    "slug": "23-how-to-track-dividend-portfolio",
    "title": "How to Track Your Dividend Portfolio",
    "category": "Investment Guides",
    "tags": []
  },
  {
    "slug": "24-how-to-screen-quality-dividend-stocks",
    "title": "How to Screen for Quality Dividend Stocks",
    "category": "Investment Guides",
    "tags": []
  },
  {
    "slug": "25-build-a-dividend-portfolio-from-scratch",
    "title": "How to Build a Dividend Portfolio from Scratch",
    "category": "Investment Guides",
    "tags": []
  },
  {
    "slug": "26-analyze-dividend-safety-before-investing",
    "title": "How to Analyze Dividend Safety Before Investing",
    "category": "Investment Guides",
    "tags": []
  },
  {
    "slug": "27-master-limited-partnerships-mlp-dividends",
    "title": "Master Limited Partnership (MLP) Dividends: Complete Guide",
    "category": "dividend-strategies",
    "tags": []
  },
  {
    "slug": "27-reinvest-dividends-for-maximum-growth",
    "title": "How to Reinvest Dividends for Maximum Growth",
    "category": "Investment Guides",
    "tags": []
  },
  {
    "slug": "28-screen-for-quality-dividend-stocks",
    "title": "How to Screen for Quality Dividend Stocks",
    "category": "Investment Guides",
    "tags": []
  },
  {
    "slug": "29-time-dividend-stock-purchases-ex-dividend-dates",
    "title": "How to Time Dividend Stock Purchases (Ex-Dividend Dates)",
    "category": "Investment Guides",
    "tags": []
  },
  {
    "slug": "30-track-your-dividend-income-and-portfolio-performance",
    "title": "How to Track Your Dividend Income and Portfolio Performance",
    "category": "Investment Guides",
    "tags": []
  },
  {
    "slug": "39-top-telecommunications-equipment-dividend-stocks-network-infrastructure",
    "title": "Top Telecommunications Equipment Dividend Stocks: Network Infrastructure",
    "category": "Dividend Investing",
    "tags": [
      "telecom equipment",
      "network stocks",
      "infrastructure stocks",
      "5G stocks"
    ]
  },
  {
    "slug": "43-handle-dividend-cuts-and-suspensions",
    "title": "How to Handle Dividend Cuts and Suspensions",
    "category": "Investment Guides",
    "tags": []
  },
  {
    "slug": "analyze-dividend-sustainability",
    "title": "How to Analyze Dividend Sustainability",
    "category": "Calc",
    "tags": []
  },
  {
    "slug": "atandt-dividend-analysis-2026-recovery-after-warner-bros-discovery-spinoff",
    "title": "AT&T Dividend Analysis 2026: Recovery After Warner Bros Discovery Spinoff",
    "category": "dividend-stocks",
    "tags": []
  },
  {
    "slug": "best-brokerage-accounts-for-dividend-investors",
    "title": "Best Brokerage Accounts for Dividend Investors",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "best-brokerage-for-dividend-investors",
    "title": "Best Brokerage for Dividend Investors",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "best-dividend-stocks-for-beginners",
    "title": "Best Dividend Stocks for Beginners",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing",
      "beginners"
    ]
  },
  {
    "slug": "best-dividend-stocks-for-passive-income-2026",
    "title": "Best Dividend Stocks for Passive Income 2026",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "best-dividend-stocks-technology-sector-2026",
    "title": "Best Dividend Stocks in Technology Sector 2026",
    "category": "Sector Analysis",
    "tags": []
  },
  {
    "slug": "best-dividend-stocks-under-50",
    "title": "Best Dividend Stocks Under $50",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "best-energy-sector-dividend-stocks",
    "title": "Best Energy Sector Dividend Stocks",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "best-healthcare-dividend-stocks",
    "title": "Best Healthcare Dividend Stocks",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "best-reit-dividend-stocks",
    "title": "Best REIT Dividend Stocks",
    "category": "Dividend Investing",
    "tags": [
      "reits",
      "dividend stocks",
      "passive income",
      "real estate"
    ]
  },
  {
    "slug": "best-technology-dividend-stocks-for-retirement-2026",
    "title": "Best Technology Dividend Stocks for Retirement 2026",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "best-utility-stocks-for-dividends",
    "title": "Best Utility Stocks for Dividends",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "blue-chip-dividend-stocks",
    "title": "Blue Chip Dividend Stocks",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "bmy-dividend-analysis",
    "title": "Bristol-Myers Squibb analysis - BMY dividend pharma",
    "category": "Dividend Stocks",
    "tags": []
  },
  {
    "slug": "building-a-dividend-ladder",
    "title": "Building a Dividend Ladder",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "building-a-dividend-ladder-for-monthly-income",
    "title": "Building a Dividend Ladder for Monthly Income",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "canadian-dividend-stocks-for-us-investors",
    "title": "Canadian Dividend Stocks for US Investors",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "consumer-staples-dividend-stocks",
    "title": "Consumer Staples Dividend Stocks",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "corporate-dividend-policy-analysis",
    "title": "Corporate Dividend Policy Analysis",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "covered-call-dividend-strategy-enhanced-income",
    "title": "Covered Call Dividend Strategy: Enhancing Income with Options",
    "category": "Dividend Investing Strategies",
    "tags": []
  },
  {
    "slug": "cyclical-vs-defensive-dividend-stocks",
    "title": "Cyclical vs Defensive Dividend Stocks",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "defensive-dividend-strategy-recession-protection",
    "title": "Defensive Dividend Strategy: Recession-Proof Income Protection",
    "category": "Dividend Investing Strategies",
    "tags": []
  },
  {
    "slug": "dividend-aristocrat-etfs-comparison",
    "title": "Dividend Aristocrat ETFs Comparison: Review of Top Income Funds 2026",
    "category": "Articles",
    "tags": []
  },
  {
    "slug": "dividend-aristocrats-analysis-and-rankings",
    "title": "Dividend Aristocrats Analysis and Rankings",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-aristocrats-complete-analysis",
    "title": "Dividend Aristocrats Complete Analysis",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-aristocrats-investing-strategy-2026",
    "title": "Dividend Aristocrats Strategy: Investing in Companies with 25+ Years of",
    "category": "Dividend Investing Strategies",
    "tags": []
  },
  {
    "slug": "dividend-capture-strategy",
    "title": "Dividend Capture Strategy",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-capture-strategy-explained",
    "title": "Dividend Capture Strategy Explained",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-capture-strategy-guide-advanced-trading",
    "title": "Dividend Capture Strategy: Advanced Trading Techniques for Extra Income",
    "category": "Dividend Investing Strategies",
    "tags": []
  },
  {
    "slug": "dividend-coverage-ratio-explained",
    "title": "Dividend Coverage Ratio Explained",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-etf-portfolio-strategy-passive-income",
    "title": "Dividend ETF Portfolio Strategy: Building Passive Income with Index Funds",
    "category": "Dividend Investing Strategies",
    "tags": []
  },
  {
    "slug": "dividend-growth-investing-strategy",
    "title": "Dividend Growth Investing Strategy",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-growth-investing-strategy-guide",
    "title": "Dividend Growth Investing Strategy: Complete Guide to Building Wealth",
    "category": "Dividend Investing Strategies",
    "tags": []
  },
  {
    "slug": "dividend-income-in-retirement",
    "title": "Dividend Income in Retirement",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-income-in-retirement-planning",
    "title": "Dividend Income in Retirement Planning",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-investing-for-early-retirement",
    "title": "Dividend Investing for Early Retirement",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-kings-50-years-of-increases",
    "title": "Dividend Kings 50 Years of Increases",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-kings-analysis",
    "title": "Dividend Kings Analysis",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-ladder-strategy-monthly-income-stream",
    "title": "Dividend Ladder Strategy: Creating Monthly Income from Quarterly Payers",
    "category": "Dividend Investing Strategies",
    "tags": []
  },
  {
    "slug": "dividend-momentum-strategy-outperforming-stocks",
    "title": "Dividend Momentum Strategy: Riding Outperforming Dividend Stocks",
    "category": "Dividend Investing Strategies",
    "tags": []
  },
  {
    "slug": "dividend-paying-blue-chip-stocks",
    "title": "Dividend Paying Blue Chip Stocks",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-portfolio-allocation-strategy-by-age",
    "title": "Dividend Portfolio Allocation Strategy: Optimal Asset Mix by Age and Goals",
    "category": "Dividend Investing Strategies",
    "tags": []
  },
  {
    "slug": "dividend-reinvestment-plans-drips-explained",
    "title": "Dividend Reinvestment Plans DRIPs Explained",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-reinvestment-plans-explained",
    "title": "Dividend Reinvestment Plans Explained",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-reinvestment-strategies-growth-income",
    "title": "Dividend Reinvestment Strategies: Optimizing for Growth vs. Current Income",
    "category": "Dividend Investing Strategies",
    "tags": []
  },
  {
    "slug": "dividend-safety-how-to-analyze-payout-ratios",
    "title": "Dividend Safety How to Analyze Payout Ratios",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-snowball-strategy-accelerated-growth",
    "title": "Dividend Snowball Strategy: Accelerating Income Growth Year Over Year",
    "category": "Dividend Investing Strategies",
    "tags": []
  },
  {
    "slug": "dividend-stock-screeners-and-tools",
    "title": "Dividend Stock Screeners and Tools",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-stock-screening-tools",
    "title": "Dividend Stock Screening Tools",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-stocks-during-economic-recessions",
    "title": "Dividend Stocks During Economic Recessions",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-stocks-during-recessions",
    "title": "Dividend Stocks During Recessions",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-stocks-for-beginners",
    "title": "Dividend Stocks for Beginners",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-sustainability-analysis-framework",
    "title": "Dividend Sustainability Analysis Framework",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-sustainability-framework",
    "title": "Dividend Sustainability Framework",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-tracking-methods",
    "title": "Dividend Tracking Methods",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-tracking-spreadsheet-guide",
    "title": "Dividend Tracking Spreadsheet Guide",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-value-investing-strategy-undervalued-stocks",
    "title": "Dividend Value Investing Strategy: Finding Undervalued Dividend Stocks",
    "category": "Dividend Investing Strategies",
    "tags": []
  },
  {
    "slug": "dividend-yield-vs-total-return",
    "title": "Dividend Yield vs Total Return",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "dividend-yield-vs-total-return-strategy",
    "title": "Dividend Yield vs Total Return Strategy",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "drip-investing-strategy-complete-guide",
    "title": "DRIP Investing Strategy: Complete Guide to Dividend Reinvestment Plans",
    "category": "Dividend Investing Strategies",
    "tags": []
  },
  {
    "slug": "ex-dividend-date-strategy",
    "title": "Ex-Dividend Date Strategy",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "ex-dividend-date-timing-your-purchases",
    "title": "Ex-Dividend Date Timing Your Purchases",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "financial-sector-dividend-opportunities",
    "title": "Financial Sector Dividend Opportunities",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "foreign-dividend-withholding-tax",
    "title": "Foreign Dividend Withholding Tax",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "foreign-dividend-withholding-tax-guide",
    "title": "Foreign Dividend Withholding Tax Guide",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "free-cash-flow-and-dividend-sustainability",
    "title": "Free Cash Flow and Dividend Sustainability",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "growth-stocks-that-pay-dividends",
    "title": "Growth Stocks That Pay Dividends",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "high-yield-dividend-stocks-vs-dividend-growth",
    "title": "High-Yield Dividend Stocks vs Dividend Growth",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "high-yield-dividend-strategy-risks-rewards",
    "title": "High Yield Dividend Strategy: Balancing Risk and Reward for Maximum Income",
    "category": "Dividend Investing Strategies",
    "tags": []
  },
  {
    "slug": "high-yield-vs-dividend-growth-stocks",
    "title": "High-Yield vs Dividend Growth Stocks",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "how-to-analyze-dividend-safety",
    "title": "How to Analyze Dividend Safety",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "how-to-build-a-1000-monthly-dividend-portfolio",
    "title": "How to Build a $1000 Monthly Dividend Portfolio",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "how-to-build-a-1000month-dividend-portfolio",
    "title": "How to Build a $1000/Month Dividend Portfolio",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "income-vs-growth-dividend-approach-comparison",
    "title": "Income vs Growth Dividend Approach: Which Strategy Builds More Wealth?",
    "category": "Dividend Investing Strategies",
    "tags": []
  },
  {
    "slug": "industrial-dividend-stocks-analysis",
    "title": "Industrial Dividend Stocks Analysis",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "international-dividend-investing-strategy-global-income",
    "title": "International Dividend Investing Strategy: Building Global Income Streams",
    "category": "Dividend Investing Strategies",
    "tags": []
  },
  {
    "slug": "international-dividend-stocks-analysis",
    "title": "International Dividend Stocks Analysis",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "international-dividend-stocks-worth-considering",
    "title": "International Dividend Stocks Worth Considering",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "master-limited-partnerships-for-income",
    "title": "Master Limited Partnerships for Income",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "master-limited-partnerships-mlps-dividend-guide",
    "title": "Master Limited Partnerships MLPs Dividend Guide",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "monthly-dividend-stocks-worth-buying",
    "title": "Monthly Dividend Stocks Worth Buying",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "portfolio-allocation-for-dividend-income",
    "title": "Portfolio Allocation for Dividend Income",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "portfolio-allocation-for-income",
    "title": "Portfolio Allocation for Income",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "preferred-stocks-vs-common-stock-dividends",
    "title": "Preferred Stocks vs Common Stock Dividends",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "qualified-dividends-vs-ordinary-dividends",
    "title": "Qualified Dividends vs Ordinary Dividends",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "qualified-vs-ordinary-dividends",
    "title": "Qualified vs Ordinary Dividends",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "quality-dividend-investing-strategy-sustainable-income",
    "title": "Quality Dividend Investing Strategy: Sustainable Income from Elite Companies",
    "category": "Dividend Investing Strategies",
    "tags": []
  },
  {
    "slug": "real-estate-investment-trusts-guide",
    "title": "Real Estate Investment Trusts Guide",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "real-estate-investment-trusts-reits-for-income",
    "title": "Real Estate Investment Trusts REITs for Income",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "reinvesting-dividends-compound-growth",
    "title": "Reinvesting Dividends Compound Growth",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "reinvesting-dividends-for-growth",
    "title": "Reinvesting Dividends for Growth",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "reit-dividends-complete-investment-guide",
    "title": "REIT Dividends Complete Investment Guide",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "reit-dividends-investment-guide",
    "title": "REIT Dividends Investment Guide",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "retirement-articles-index",
    "title": "Calc Retirement Planning Articles - Complete Index",
    "category": "Articles",
    "tags": []
  },
  {
    "slug": "rising-dividend-stocks-strategy-total-return",
    "title": "Rising Dividend Stocks Strategy: Total Return Through Consistent Raises",
    "category": "Dividend Investing Strategies",
    "tags": []
  },
  {
    "slug": "sector-rotation-dividend-strategy-cyclical-timing",
    "title": "Sector Rotation Dividend Strategy: Timing Cyclical Dividend Stocks",
    "category": "Dividend Investing Strategies",
    "tags": []
  },
  {
    "slug": "sector-rotation-for-dividend-investors",
    "title": "Sector Rotation for Dividend Investors",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "small-cap-dividend-opportunities",
    "title": "Small Cap Dividend Opportunities",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "small-cap-dividend-stocks-opportunities",
    "title": "Small Cap Dividend Stocks Opportunities",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "special-dividends-vs-regular-dividends",
    "title": "Special Dividends vs Regular Dividends",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "tax-efficient-dividend-investing-strategies",
    "title": "Tax-Efficient Dividend Investing: Strategies to Keep More of Your Returns",
    "category": "Dividend Investing Strategies",
    "tags": []
  },
  {
    "slug": "tax-efficient-dividend-portfolio-design",
    "title": "Tax-Efficient Dividend Portfolio Design",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "technology-dividend-stocks-guide",
    "title": "Technology Dividend Stocks Guide",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "top-dividend-etfs-vs-individual-stocks",
    "title": "Top Dividend ETFs vs Individual Stocks",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  },
  {
    "slug": "top-dividend-etfs-vs-individual-stocks-comparison",
    "title": "Top Dividend ETFs vs Individual Stocks Comparison",
    "category": "Dividend Investing",
    "tags": [
      "dividend stocks",
      "passive income",
      "investing"
    ]
  }
]
